spring:
  application:
    name: dineInOrderAPI

  datasource:
    url: jdbc:mysql://localhost:3306/dine-In?createDatabaseIfNotExist=true
    username: root
    password: Akash@2001
  jpa:
    show-sql: true
    hibernate:
     ddl-auto:update
